<?xml version="1.0"?>


<!--ParticleSystemDescription-->

<ParticleSystemName version="2">
  <Node name="Smoke Emiter" particleType="Normal" lifetimeValue="2.0" lifetimeVariance="0.00" periodValue="0" periodVariance="0" lifetimeType="ParentParticleTagpoint" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="0" offsetXVariance="0" offsetXInterpolatorType="1" offsetXFinalValue="0" offsetXFinalVariance="0" offsetYValue="0" offsetYVariance="0" offsetYInterpolatorType="1" offsetYFinalValue="0" offsetYFinalVariance="0" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="0" yawVariance="0" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="1" velocityBasedOrientation="False" trackParentPosition="True" trackParentOrientation="True" enableGraphics="False" enableRibbonTrail="False" enableEmitter="True" emitterIntervalValue="0.25" emitterIntervalVariance="0.00" emitterIntervalInterpolatorType="0" emitterSpawnNumberValue="1" emitterSpawnNumberVariance="0" emitterSpawnNumberInterpolatorType="0" emitterVelocityValue="0.0" emitterVelocityVariance="0.00" emitterVelocityInterpolatorType="0" emitUponDeath="False" emitterSpawnDelayValue="0.0" emitterSpawnDelayVariance="0.0" randomizeVelocityPerParticleInstance="False" emitterShape="0" fixedSampling="False" enableSoundEffect="False" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="0" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="15.0" cameraShakeRangeVariance="0.0" spinAroundCenterValue="0" spinAroundCenterVariance="0" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="Always" createOffscreen="False" emitOffscreen="False" updateOffscreen="False">
    <Node name="Graphic" particleType="Normal" lifetimeValue="2.7" lifetimeVariance="0.60" periodValue="0" periodVariance="0" lifetimeType="Fixed" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="0" offsetXVariance="0" offsetXInterpolatorType="7" offsetXFinalValue="1.40" offsetXFinalVariance="0.60" offsetXCustomCurveSampleData="0.001979947,0.1039314,0.2888367,0.504968,0.7509873," offsetXCustomCurveEditorData="0,1,0.05999997,0.3934282,0.7185189,-0.89,1,0,-0.99,|0,0,1,2,2," offsetYValue="0" offsetYVariance="0" offsetYInterpolatorType="7" offsetYFinalValue="0.7" offsetYFinalVariance="0.20" offsetYCustomCurveSampleData="0.03583622,0.3224787,0.4954428,0.62854,0.7482249,0.835416,0.9156954," offsetYCustomCurveEditorData="0,1,0.96,0.309947,0.4814816,-0.9899999,1,0,-0.79,|0,0,1,2,2," offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="-360" yawVariance="720" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="0" velocityBasedOrientation="False" trackParentPosition="False" trackParentOrientation="False" enableGraphics="True" depthSort="False" uniformScaling="True" scaleXValue="0.1" scaleXVariance="0.00" scaleXInterpolatorType="2" scaleXFinalValue="0.9" scaleXFinalVariance="0.00" scaleYValue="0.1" scaleYVariance="0.00" scaleYInterpolatorType="2" scaleYFinalValue="0.9" scaleYFinalVariance="0.00" texCoordUValue="0" texCoordUVariance="0" texCoordUInterpolatorType="0" texCoordVValue="0" texCoordVVariance="0" texCoordVInterpolatorType="0" colorColorKeyTime1="0.071" colorOpacityKeyTime1="0.212" colorOpacityKeyTime2="0.525" colorColorKeys="5F5F5FFFFFFFFFFFFF" colorColorVarianceKeys="000000000000000000" colorOpacityKeys="00FFFF00" colorOpacityVarianceKeys="00000000" colorCyclic="False" blendMode="alpha" renderMode="ThreeDimensional" anchorX="0.5" anchorY="0.5" appearanceFile="Smoke.png" animationName="" loopAnimation="False" animationFPS="30" renderPass="main" enableRibbonTrail="False" enableEmitter="False" enableSoundEffect="False" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="0" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="0" cameraShakeRangeVariance="0" spinAroundCenterValue="-0.06" spinAroundCenterVariance="0.120" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="Always" createOffscreen="False" emitOffscreen="False" updateOffscreen="False" />
  </Node>
</ParticleSystemName>