<?xml version="1.0"?>


<!--ParticleSystemDescription-->

<ParticleSystemName version="2" playsWhilePaused="True">
  <Node name="Emitter" particleType="Normal" lifetimeValue="1.0" lifetimeVariance="0.0" periodValue="0.0" periodVariance="0.00" lifetimeType="Infinite" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="0" offsetXVariance="0" offsetXInterpolatorType="0" offsetYValue="0" offsetYVariance="0" offsetYInterpolatorType="0" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="0" yawVariance="0" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="0" velocityBasedOrientation="False" trackParentPosition="False" trackParentOrientation="False" enableGraphics="False" enableRibbonTrail="False" enableEmitter="True" emitterIntervalValue="9999.0" emitterIntervalVariance="0.00" emitterIntervalInterpolatorType="0" emitterSpawnNumberValue="2" emitterSpawnNumberVariance="2" emitterSpawnNumberInterpolatorType="0" emitterVelocityValue="0.0" emitterVelocityVariance="0.00" emitterVelocityInterpolatorType="0" emitUponDeath="False" emitterSpawnDelayValue="0" emitterSpawnDelayVariance="0" randomizeVelocityPerParticleInstance="False" emitterShape="1" emitterShapeOuterWidth="0.1" emitterShapeOuterHeight="0.1" emitterShapeOuterDepth="0" fixedSampling="False" enableSoundEffect="False" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="0" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="0" cameraShakeRangeVariance="0" spinAroundCenterValue="0" spinAroundCenterVariance="0" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="Always" createOffscreen="False" emitOffscreen="False" updateOffscreen="False">
    <Node name="Bee" particleType="Normal" lifetimeValue="10" lifetimeVariance="0" periodValue="1.60" periodVariance="0.80" lifetimeType="Infinite" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="-0.03" offsetXVariance="0.060" offsetXInterpolatorType="6" offsetXFinalValue="-0.03" offsetXFinalVariance="0.060" offsetYValue="0" offsetYVariance="0" offsetYInterpolatorType="0" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="0" yawVariance="0" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="1" velocityBasedOrientation="True" trackParentPosition="False" trackParentOrientation="True" enableGraphics="True" depthSort="False" uniformScaling="True" scaleXValue="0.03" scaleXVariance="0.00" scaleXInterpolatorType="6" scaleXFinalValue="0.05" scaleXFinalVariance="0.00" scaleYValue="0.03" scaleYVariance="0.00" scaleYInterpolatorType="6" scaleYFinalValue="0.05" scaleYFinalVariance="0.00" texCoordUValue="0" texCoordUVariance="0" texCoordUInterpolatorType="0" texCoordVValue="0" texCoordVVariance="0" texCoordVInterpolatorType="0" colorColorKeys="800000800000" colorColorVarianceKeys="000000000000" colorOpacityKeys="8D8D" colorOpacityVarianceKeys="0000" colorCyclic="False" blendMode="alpha" renderMode="ThreeDimensional" anchorX="0.5" anchorY="0.5" appearanceFile="Ambient_Bee.png" animationName="" loopAnimation="False" animationFPS="30" renderPass="main" enableRibbonTrail="False" enableEmitter="False" enableSoundEffect="False" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="0" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="2.4" cameraShakeRangeVariance="0.0" spinAroundCenterValue="0" spinAroundCenterVariance="0" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0.00" spinAroundPivotVariance="0.600" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="True" randomDirectionXValue="0.1" randomDirectionXVariance="0.0" randomDirectionXInterpolatorType="0" randomDirectionYValue="0.1" randomDirectionYVariance="0.0" randomDirectionYInterpolatorType="0" randomDirectionZValue="0" randomDirectionZVariance="0" randomDirectionZInterpolatorType="0" randomIntervalValue="0.1" randomIntervalVariance="0.0" randomPauseIntervalValue="0.1" randomPauseIntervalVariance="0.0" priority="Always" createOffscreen="False" emitOffscreen="False" updateOffscreen="False" />
  </Node>
</ParticleSystemName>