<?xml version="1.0"?>


<!--ParticleSystemDescription-->

<ParticleSystemName version="2" savedCameraRotation="-29">
  <Node name="Spark" particleType="Normal" lifetimeValue="0.2" lifetimeVariance="0.0" periodValue="0.0" periodVariance="0.0" lifetimeType="ParentParticleTagpoint" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="0" offsetXVariance="0" offsetXInterpolatorType="0" offsetYValue="0" offsetYVariance="0" offsetYInterpolatorType="0" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="180" yawVariance="0" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="0" velocityBasedOrientation="False" trackParentPosition="False" trackParentOrientation="False" enableGraphics="False" enableRibbonTrail="False" enableEmitter="True" emitterIntervalValue="0.02" emitterIntervalVariance="0.400" emitterIntervalInterpolatorType="0" emitterSpawnNumberValue="2" emitterSpawnNumberVariance="4" emitterSpawnNumberInterpolatorType="0" emitterVelocityValue="-1" emitterVelocityVariance="2" emitterVelocityInterpolatorType="0" emitUponDeath="False" emitterSpawnDelayValue="0" emitterSpawnDelayVariance="0" randomizeVelocityPerParticleInstance="False" emitterShape="0" fixedSampling="False" enableSoundEffect="False" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="0" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="15.0" cameraShakeRangeVariance="0.0" spinAroundCenterValue="0" spinAroundCenterVariance="0" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="Low" createOffscreen="False" emitOffscreen="False" updateOffscreen="False">
    <Node name="New" particleType="Normal" lifetimeValue="0.3" lifetimeVariance="0.80" periodValue="0.0" periodVariance="0.0" lifetimeType="Fixed" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="-3" offsetXVariance="6" offsetXInterpolatorType="0" offsetYValue="-0.20" offsetYVariance="0.400" offsetYInterpolatorType="2" offsetYFinalValue="-1.5" offsetYFinalVariance="1.00" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="-180" yawVariance="360" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="0" velocityBasedOrientation="False" trackParentPosition="False" trackParentOrientation="False" enableGraphics="True" depthSort="False" uniformScaling="True" scaleXValue="0.10" scaleXVariance="0.100" scaleXInterpolatorType="2" scaleXFinalValue="0.0" scaleXFinalVariance="0.00" scaleYValue="0.10" scaleYVariance="0.100" scaleYInterpolatorType="2" scaleYFinalValue="0.0" scaleYFinalVariance="0.00" texCoordUValue="0" texCoordUVariance="0" texCoordUInterpolatorType="0" texCoordVValue="0" texCoordVVariance="0" texCoordVInterpolatorType="0" colorOpacityKeyTime1="0.081" colorOpacityKeyTime2="0.273" colorOpacityKeyTime3="0.505" colorOpacityKeyTime4="0.697" colorOpacityKeyTime5="0.869" colorColorKeys="FFF204FF8040" colorColorVarianceKeys="000000000000" colorOpacityKeys="00FF4384305400" colorOpacityVarianceKeys="00000000000000" colorCyclic="False" blendMode="alphaAdd" renderMode="ThreeDimensional" anchorX="0.5" anchorY="0.5" appearanceFile="Glow.jpg" animationName="idle" loopAnimation="True" animationFPS="30.0" renderPass="main" enableRibbonTrail="False" enableEmitter="False" enableSoundEffect="False" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="0" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="15.0" cameraShakeRangeVariance="0.0" spinAroundCenterValue="-1" spinAroundCenterVariance="2" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="Low" createOffscreen="False" emitOffscreen="False" updateOffscreen="False" />
  </Node>
</ParticleSystemName>