<?xml version="1.0"?>


<!--ParticleSystemDescription-->

<ParticleSystemName version="2">
  <Node name="Tower_Flame" particleType="Normal" lifetimeValue="1" lifetimeVariance="0" periodValue="0.0" periodVariance="0.0" lifetimeType="ParentParticleTagpoint" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="0" offsetXVariance="0" offsetXInterpolatorType="0" offsetYValue="0.00" offsetYVariance="0.0" offsetYInterpolatorType="0" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="0" yawVariance="0" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="1" velocityBasedOrientation="False" trackParentPosition="True" trackParentOrientation="True" enableGraphics="False" enableRibbonTrail="False" enableEmitter="True" emitterIntervalValue="0.5" emitterIntervalVariance="0.00" emitterIntervalInterpolatorType="0" emitterSpawnNumberValue="1" emitterSpawnNumberVariance="0" emitterSpawnNumberInterpolatorType="0" emitterVelocityValue="0.0" emitterVelocityVariance="0.0" emitterVelocityInterpolatorType="0" emitUponDeath="False" emitterSpawnDelayValue="0" emitterSpawnDelayVariance="0" randomizeVelocityPerParticleInstance="False" emitterShape="0" fixedSampling="False" enableSoundEffect="True" soundEventPath="Towers/Tower_Gas/Impact" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="0" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="15.0" cameraShakeRangeVariance="0.0" spinAroundCenterValue="0" spinAroundCenterVariance="0" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="Always" createOffscreen="False" emitOffscreen="False" updateOffscreen="False">
    <Node name="placement" particleType="Normal" lifetimeValue="1" lifetimeVariance="0" periodValue="0.0" periodVariance="0.0" lifetimeType="Fixed" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="-0.2" offsetXVariance="0.40" offsetXInterpolatorType="0" offsetYValue="-0.10" offsetYVariance="0.20" offsetYInterpolatorType="0" offsetZValue="-0.05" offsetZVariance="0.100" offsetZInterpolatorType="0" yawValue="-180" yawVariance="360" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="1" velocityBasedOrientation="False" trackParentPosition="True" trackParentOrientation="True" enableGraphics="True" depthSort="False" uniformScaling="True" scaleXValue="0.2" scaleXVariance="0.20" scaleXInterpolatorType="2" scaleXFinalValue="0.3" scaleXFinalVariance="0.20" scaleYValue="0.2" scaleYVariance="0.20" scaleYInterpolatorType="2" scaleYFinalValue="0.3" scaleYFinalVariance="0.20" texCoordUValue="0" texCoordUVariance="0" texCoordUInterpolatorType="0" texCoordVValue="0" texCoordVVariance="0" texCoordVInterpolatorType="0" colorOpacityKeyTime1="0.182" colorColorKeys="7DC034678639" colorColorVarianceKeys="000000000000" colorOpacityKeys="003400" colorOpacityVarianceKeys="000000" colorCyclic="False" blendMode="alpha" renderMode="ThreeDimensional" anchorX="0.5" anchorY="0.5" appearanceFile="GasCloud.jpg" animationName="death" loopAnimation="False" animationFPS="24.0" renderPass="main" enableRibbonTrail="False" enableEmitter="False" enableSoundEffect="False" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="2" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="15.0" cameraShakeRangeVariance="0.0" spinAroundCenterValue="0" spinAroundCenterVariance="0" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="High" createOffscreen="False" emitOffscreen="False" updateOffscreen="False" />
  </Node>
</ParticleSystemName>