<?xml version="1.0"?>


<!--ParticleSystemDescription-->

<ParticleSystemName version="2" savedCameraRotation="-29" playsWhilePaused="True" drawsOverGround="True">
  <Node name="Emitter" particleType="Normal" lifetimeValue="1.2" lifetimeVariance="0.0" periodValue="0.0" periodVariance="0.00" lifetimeType="Fixed" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="0" offsetXVariance="0" offsetXInterpolatorType="0" offsetYValue="0" offsetYVariance="0" offsetYInterpolatorType="0" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="0" yawVariance="0" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="-30" rollVariance="60" rollInterpolatorType="0" coordinateSystem="0" velocityBasedOrientation="False" trackParentPosition="False" trackParentOrientation="False" enableGraphics="False" enableRibbonTrail="False" enableEmitter="True" emitterIntervalValue="9999" emitterIntervalVariance="0" emitterIntervalInterpolatorType="0" emitterSpawnNumberValue="1" emitterSpawnNumberVariance="0" emitterSpawnNumberInterpolatorType="0" emitterVelocityValue="3.9" emitterVelocityVariance="0.60" emitterVelocityInterpolatorType="0" emitUponDeath="False" emitterSpawnDelayValue="0" emitterSpawnDelayVariance="0" randomizeVelocityPerParticleInstance="False" emitterShape="0" fixedSampling="False" enableSoundEffect="False" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="0" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="15.0" cameraShakeRangeVariance="0.0" spinAroundCenterValue="0" spinAroundCenterVariance="0" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="Always" createOffscreen="False" emitOffscreen="False" updateOffscreen="False">
    <Node name="Text" particleType="Normal" lifetimeValue="0.8" lifetimeVariance="0.0" periodValue="0.0" periodVariance="0.00" lifetimeType="Fixed" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="0" offsetXVariance="0" offsetXInterpolatorType="0" offsetYValue="0" offsetYVariance="0" offsetYInterpolatorType="3" offsetYFinalValue="-1.5" offsetYFinalVariance="0.0" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="0" yawVariance="0" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="0" velocityBasedOrientation="False" trackParentPosition="False" trackParentOrientation="False" enableGraphics="True" depthSort="False" uniformScaling="True" scaleXValue="0.5" scaleXVariance="0.0" scaleXInterpolatorType="4" scaleXFinalValue="0.88" scaleXFinalVariance="0.0" scaleYValue="0.5" scaleYVariance="0.0" scaleYInterpolatorType="4" scaleYFinalValue="0.88" scaleYFinalVariance="0.0" texCoordUValue="0" texCoordUVariance="0" texCoordUInterpolatorType="0" texCoordVValue="0" texCoordVVariance="0" texCoordVInterpolatorType="0" colorOpacityKeyTime1="0.677" colorColorKeys="FFFFFFFFFFFF" colorColorVarianceKeys="000000000000" colorOpacityKeys="FFFF00" colorOpacityVarianceKeys="000000" colorCyclic="False" blendMode="alpha" renderMode="ThreeDimensional" anchorX="0.5" anchorY="0.5" appearanceFile="Coin.asc" animationName="idle" loopAnimation="True" animationFPS="30" renderPass="main" fontFileName="StencilYellow10.asc" fontLeading="0" fontTracking="-7" particleText="$$(LastKilledReward)" translateOnce="True" textEffect="None" enableRibbonTrail="False" enableEmitter="False" enableSoundEffect="False" massValue="5" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="2" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="15.0" cameraShakeRangeVariance="0.0" spinAroundCenterValue="0" spinAroundCenterVariance="0" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="Always" createOffscreen="False" emitOffscreen="False" updateOffscreen="False" />
  </Node>
</ParticleSystemName>