<?xml version="1.0"?>


<!--ParticleSystemDescription-->

<ParticleSystemName version="2">
  <Node name="Emitter" particleType="Normal" lifetimeValue="0.7" lifetimeVariance="0.0" periodValue="0" periodVariance="0" lifetimeType="Fixed" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="0" offsetXVariance="0" offsetXInterpolatorType="0" offsetYValue="0" offsetYVariance="0" offsetYInterpolatorType="0" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="-360" yawVariance="720" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="1" velocityBasedOrientation="False" trackParentPosition="True" trackParentOrientation="False" enableGraphics="False" enableRibbonTrail="False" enableEmitter="True" emitterIntervalValue="9999" emitterIntervalVariance="0" emitterIntervalInterpolatorType="0" emitterSpawnNumberValue="12" emitterSpawnNumberVariance="0" emitterSpawnNumberInterpolatorType="0" emitterVelocityValue="0.7" emitterVelocityVariance="0.60" emitterVelocityInterpolatorType="0" emitUponDeath="False" emitterSpawnDelayValue="0.2" emitterSpawnDelayVariance="0.0" randomizeVelocityPerParticleInstance="False" emitterShape="1" emitterShapeOuterWidth="0.5" emitterShapeOuterHeight="0.5" emitterShapeOuterDepth="0" fixedSampling="False" enableSoundEffect="False" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="0" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="15.0" cameraShakeRangeVariance="0.0" spinAroundCenterValue="0" spinAroundCenterVariance="0" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="Always" createOffscreen="False" emitOffscreen="False" updateOffscreen="False">
    <Node name="Bees!" particleType="Normal" lifetimeValue="0.8" lifetimeVariance="0.40" periodValue="0" periodVariance="0" lifetimeType="Fixed" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="-0.3" offsetXVariance="0.60" offsetXInterpolatorType="0" offsetYValue="-0.3" offsetYVariance="0.60" offsetYInterpolatorType="0" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="0" yawVariance="0" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="1" velocityBasedOrientation="False" trackParentPosition="True" trackParentOrientation="False" enableGraphics="True" depthSort="False" uniformScaling="True" scaleXValue="0.06" scaleXVariance="0.040" scaleXInterpolatorType="0" scaleYValue="0.06" scaleYVariance="0.040" scaleYInterpolatorType="0" texCoordUValue="0" texCoordUVariance="0" texCoordUInterpolatorType="0" texCoordVValue="0" texCoordVVariance="0" texCoordVInterpolatorType="0" colorColorKeys="000000000000" colorColorVarianceKeys="000000000000" colorOpacityKeys="FF00" colorOpacityVarianceKeys="0000" colorCyclic="False" blendMode="alpha" renderMode="ThreeDimensional" anchorX="0.5" anchorY="0.5" appearanceFile="Glow.jpg" animationName="" loopAnimation="False" animationFPS="30" renderPass="main" enableRibbonTrail="True" ribbonTrailRenderPass="main" ribbonBlendMode="alpha" ribbonMaxLengthValue="0.20" ribbonMaxLengthVariance="0.100" ribbonSegmentWidthValue="-0.08" ribbonSegmentWidthVariance="0.160" ribbonMaxSegmentsValue="50" ribbonMaxSegmentsVariance="0" ribbonDecayInterpolatorValue="0.15" ribbonDecayInterpolatorVariance="0.0" ribbonDecayInterpolatorInterpolatorType="1" ribbonDecayInterpolatorFinalValue="0" ribbonDecayInterpolatorFinalVariance="0" ribbonDecayStartOffset="0" ribbonColorColorKeys="FFFF00000000" ribbonColorColorVarianceKeys="000000000000" ribbonColorOpacityKeys="FF00" ribbonColorOpacityVarianceKeys="0000" ribbonColorCyclic="False" enableEmitter="False" enableSoundEffect="False" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="0" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="0" cameraShakeRangeVariance="0" spinAroundCenterValue="-1" spinAroundCenterVariance="4" spinAroundCenterInterpolatorType="2" spinAroundCenterFinalValue="-2.5" spinAroundCenterFinalVariance="4.0" spinAroundPivotValue="2.6" spinAroundPivotVariance="0.80" spinAroundPivotInterpolatorType="2" spinAroundPivotFinalValue="0.40" spinAroundPivotFinalVariance="0.400" collidesWithTerrain="False" applyRandomVelocity="False" priority="Always" createOffscreen="False" emitOffscreen="False" updateOffscreen="False" />
  </Node>
</ParticleSystemName>