<?xml version="1.0"?>


<!--ParticleSystemDescription-->

<ParticleSystemName version="2" drawsOverGround="True">
  <Node name="Root" particleType="Normal" lifetimeValue="1.0" lifetimeVariance="0.0" periodValue="0" periodVariance="0" lifetimeType="Fixed" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="0" offsetXVariance="0" offsetXInterpolatorType="0" offsetYValue="0" offsetYVariance="0" offsetYInterpolatorType="0" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="-360" yawVariance="720" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="1" velocityBasedOrientation="False" trackParentPosition="True" trackParentOrientation="True" enableGraphics="True" depthSort="False" uniformScaling="True" scaleXValue="4" scaleXVariance="0" scaleXInterpolatorType="0" scaleYValue="4" scaleYVariance="0" scaleYInterpolatorType="0" texCoordUValue="0" texCoordUVariance="0" texCoordUInterpolatorType="0" texCoordVValue="0" texCoordVVariance="0" texCoordVInterpolatorType="0" colorColorKeys="48FB2800FF40" colorColorVarianceKeys="000000000000" colorOpacityKeys="FF00" colorOpacityVarianceKeys="0000" colorCyclic="False" blendMode="alphaAdd" renderMode="ThreeDimensional" anchorX="0.5" anchorY="0.5" appearanceFile="explosion_air.asc" animationName="death" loopAnimation="False" animationFPS="30" renderPass="main" enableRibbonTrail="False" enableEmitter="True" emitterIntervalValue="9999" emitterIntervalVariance="0" emitterIntervalInterpolatorType="0" emitterSpawnNumberValue="5" emitterSpawnNumberVariance="0" emitterSpawnNumberInterpolatorType="0" emitterVelocityValue="5.0" emitterVelocityVariance="0.0" emitterVelocityInterpolatorType="0" emitUponDeath="False" emitterSpawnDelayValue="0" emitterSpawnDelayVariance="0" randomizeVelocityPerParticleInstance="False" emitterShape="0" fixedSampling="False" enableSoundEffect="True" soundEventPath="Towers/Tower_Plasma/Impact" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="0" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="15.0" cameraShakeRangeVariance="0.0" spinAroundCenterValue="0" spinAroundCenterVariance="0" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="Medium" createOffscreen="False" emitOffscreen="False" updateOffscreen="False">
    <Node name="sparks" particleType="Normal" lifetimeValue="0.1" lifetimeVariance="0.20" periodValue="0" periodVariance="0" lifetimeType="Fixed" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="0" offsetXVariance="0" offsetXInterpolatorType="0" offsetYValue="0" offsetYVariance="0" offsetYInterpolatorType="0" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="0" yawVariance="0" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="0" velocityBasedOrientation="False" trackParentPosition="False" trackParentOrientation="False" enableGraphics="True" depthSort="False" uniformScaling="True" scaleXValue="0.04" scaleXVariance="0.100" scaleXInterpolatorType="0" scaleYValue="0.04" scaleYVariance="0.100" scaleYInterpolatorType="0" texCoordUValue="0" texCoordUVariance="0" texCoordUInterpolatorType="0" texCoordVValue="0" texCoordVVariance="0" texCoordVInterpolatorType="0" colorColorKeys="00FF0000FF00" colorColorVarianceKeys="000000000000" colorOpacityKeys="FFFF" colorOpacityVarianceKeys="0000" colorCyclic="False" blendMode="alphaAdd" renderMode="ThreeDimensional" anchorX="0.5" anchorY="0.5" appearanceFile="Glow.png" animationName="" loopAnimation="False" animationFPS="30" renderPass="main" enableRibbonTrail="False" enableEmitter="False" enableSoundEffect="False" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="5" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="15.0" cameraShakeRangeVariance="0.0" spinAroundCenterValue="0" spinAroundCenterVariance="0" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="Medium" createOffscreen="False" emitOffscreen="False" updateOffscreen="False" />
  </Node>
</ParticleSystemName>