<?xml version="1.0"?>


<!--ParticleSystemDescription-->

<ParticleSystemName version="2" playsWhilePaused="True" drawsOverGround="True">
  <Node name="Root" particleType="Normal" lifetimeValue="1.0" lifetimeVariance="0.00" periodValue="3.0" periodVariance="0.0" lifetimeType="ParentParticleTagpoint" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="0" offsetXVariance="0" offsetXInterpolatorType="0" offsetYValue="0.05" offsetYVariance="0.0" offsetYInterpolatorType="0" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="90" yawVariance="0" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="1" velocityBasedOrientation="False" trackParentPosition="True" trackParentOrientation="False" enableGraphics="True" depthSort="False" uniformScaling="True" scaleXValue="0.6" scaleXVariance="0.0" scaleXInterpolatorType="6" scaleXFinalValue="0.8" scaleXFinalVariance="0.00" scaleYValue="0.6" scaleYVariance="0.0" scaleYInterpolatorType="6" scaleYFinalValue="0.8" scaleYFinalVariance="0.00" texCoordUValue="0" texCoordUVariance="0" texCoordUInterpolatorType="0" texCoordVValue="0" texCoordVVariance="0" texCoordVInterpolatorType="0" colorOpacityKeyTime1="0.475" colorColorKeys="F38FFCF38FFC" colorColorVarianceKeys="000000000000" colorOpacityKeys="FF81FF" colorOpacityVarianceKeys="000000" colorCyclic="False" blendMode="alphaAdd" renderMode="ThreeDimensional" anchorX="0.5" anchorY="0.5" appearanceFile="Glow.png" animationName="" loopAnimation="False" animationFPS="30" renderPass="main" enableRibbonTrail="False" enableEmitter="True" emitterIntervalValue="0.7" emitterIntervalVariance="0.00" emitterIntervalInterpolatorType="0" emitterSpawnNumberValue="1" emitterSpawnNumberVariance="0" emitterSpawnNumberInterpolatorType="0" emitterVelocityValue="0.0" emitterVelocityVariance="0.0" emitterVelocityInterpolatorType="0" emitUponDeath="False" emitterSpawnDelayValue="0" emitterSpawnDelayVariance="0" randomizeVelocityPerParticleInstance="False" emitterShape="0" fixedSampling="False" enableSoundEffect="False" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="0" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="15.0" cameraShakeRangeVariance="0.0" spinAroundCenterValue="0.06" spinAroundCenterVariance="0.0" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="Low" createOffscreen="False" emitOffscreen="False" updateOffscreen="False">
    <Node name="Bits" particleType="Normal" lifetimeValue="0.8" lifetimeVariance="0.40" periodValue="0.0" periodVariance="0.0" lifetimeType="Fixed" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="0" offsetXVariance="0" offsetXInterpolatorType="2" offsetXFinalValue="0" offsetXFinalVariance="0" offsetYValue="0" offsetYVariance="0" offsetYInterpolatorType="2" offsetYFinalValue="0" offsetYFinalVariance="0" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="-360" yawVariance="720" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="1" velocityBasedOrientation="False" trackParentPosition="True" trackParentOrientation="False" enableGraphics="True" depthSort="False" uniformScaling="True" scaleXValue="0.97" scaleXVariance="0.060" scaleXInterpolatorType="1" scaleXFinalValue="0.05" scaleXFinalVariance="0.00" scaleYValue="0.97" scaleYVariance="0.060" scaleYInterpolatorType="1" scaleYFinalValue="0.05" scaleYFinalVariance="0.00" texCoordUValue="0" texCoordUVariance="0" texCoordUInterpolatorType="0" texCoordVValue="0" texCoordVVariance="0" texCoordVInterpolatorType="0" colorOpacityKeyTime1="0.778" colorColorKeys="FFFFFFC284FB" colorColorVarianceKeys="000000000000" colorOpacityKeys="00DA00" colorOpacityVarianceKeys="000000" colorCyclic="False" blendMode="alphaAdd" renderMode="ThreeDimensional" anchorX="0.5" anchorY="0.5" appearanceFile="rad_orbs.jpg" animationName="" loopAnimation="False" animationFPS="30" renderPass="main" enableRibbonTrail="False" enableEmitter="False" enableSoundEffect="False" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="0" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="15.0" cameraShakeRangeVariance="0.0" spinAroundCenterValue="0" spinAroundCenterVariance="0" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="Low" createOffscreen="False" emitOffscreen="False" updateOffscreen="False" />
  </Node>
</ParticleSystemName>