<?xml version="1.0"?>


<!--ParticleSystemDescription-->

<ParticleSystemName version="2" playsWhilePaused="True" drawsOverGround="True">
  <Node name="Tower_Placement" particleType="Normal" lifetimeValue="1.0" lifetimeVariance="0.0" periodValue="0" periodVariance="0" lifetimeType="Fixed" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="0" offsetXVariance="0" offsetXInterpolatorType="0" offsetYValue="0" offsetYVariance="0" offsetYInterpolatorType="0" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="0" yawVariance="0" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="1" velocityBasedOrientation="False" trackParentPosition="True" trackParentOrientation="False" enableGraphics="True" depthSort="False" uniformScaling="False" scaleXValue="3.12" scaleXVariance="0.0" scaleXInterpolatorType="0" scaleYValue="3.9" scaleYVariance="0.0" scaleYInterpolatorType="0" texCoordUValue="0" texCoordUVariance="0" texCoordUInterpolatorType="0" texCoordVValue="0" texCoordVVariance="0" texCoordVInterpolatorType="0" colorColorKeys="FFFFFFFFFFFF" colorColorVarianceKeys="000000000000" colorOpacityKeys="5B00" colorOpacityVarianceKeys="0000" colorCyclic="False" blendMode="alpha" renderMode="ThreeDimensional" anchorX="0.5" anchorY="0.5" appearanceFile="smokering.asc" animationName="death" loopAnimation="False" animationFPS="40" renderPass="main" enableRibbonTrail="False" enableEmitter="True" emitterIntervalValue="1.0" emitterIntervalVariance="0.0" emitterIntervalInterpolatorType="0" emitterSpawnNumberValue="1" emitterSpawnNumberVariance="0" emitterSpawnNumberInterpolatorType="0" emitterVelocityValue="0" emitterVelocityVariance="0" emitterVelocityInterpolatorType="0" emitUponDeath="False" emitterSpawnDelayValue="0" emitterSpawnDelayVariance="0" randomizeVelocityPerParticleInstance="False" emitterShape="0" fixedSampling="False" enableSoundEffect="True" soundEventPath="UI/In_Game/Tower_Drag_Success" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="0" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="15.0" cameraShakeRangeVariance="0.0" spinAroundCenterValue="0" spinAroundCenterVariance="0" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="Always" createOffscreen="False" emitOffscreen="False" updateOffscreen="False">
    <Node name="Tower_Placement" particleType="Normal" lifetimeValue="1.0" lifetimeVariance="0.0" periodValue="0" periodVariance="0" lifetimeType="Fixed" tesselateSourceToTarget="False" sourceToTargetSnapToCardinals="False" offsetXValue="0" offsetXVariance="0" offsetXInterpolatorType="0" offsetYValue="0" offsetYVariance="0" offsetYInterpolatorType="0" offsetZValue="0" offsetZVariance="0" offsetZInterpolatorType="0" yawValue="0" yawVariance="0" yawInterpolatorType="0" pitchValue="0" pitchVariance="0" pitchInterpolatorType="0" rollValue="0" rollVariance="0" rollInterpolatorType="0" coordinateSystem="1" velocityBasedOrientation="False" trackParentPosition="True" trackParentOrientation="False" enableGraphics="True" depthSort="False" uniformScaling="False" scaleXValue="3.12" scaleXVariance="0.0" scaleXInterpolatorType="0" scaleYValue="3.9" scaleYVariance="0.0" scaleYInterpolatorType="0" texCoordUValue="0" texCoordUVariance="0" texCoordUInterpolatorType="0" texCoordVValue="0" texCoordVVariance="0" texCoordVInterpolatorType="0" colorColorKeys="FFFFFFFFFFFF" colorColorVarianceKeys="000000000000" colorOpacityKeys="A900" colorOpacityVarianceKeys="0000" colorCyclic="False" blendMode="alphaAdd" renderMode="ThreeDimensional" anchorX="0.5" anchorY="0.5" appearanceFile="smokering.asc" animationName="death" loopAnimation="False" animationFPS="40" renderPass="main" enableRibbonTrail="False" enableEmitter="False" enableSoundEffect="False" massValue="0" massVariance="0" aeroDynamicsValue="0" aeroDynamicsVariance="0" dampingValue="0" dampingVariance="0" cameraShakeValue="0" cameraShakeVariance="0" cameraShakeRangeValue="15.0" cameraShakeRangeVariance="0.0" spinAroundCenterValue="0" spinAroundCenterVariance="0" spinAroundCenterInterpolatorType="0" spinAroundPivotValue="0" spinAroundPivotVariance="0" spinAroundPivotInterpolatorType="0" collidesWithTerrain="False" applyRandomVelocity="False" priority="Always" createOffscreen="False" emitOffscreen="False" updateOffscreen="False" />
  </Node>
</ParticleSystemName>